# site settings
title: The Roma Project
subtitle: The Roma People's Project at Columbia University
email: cristianagrigore@columbia.edu
description: "The Roma People's Project at Columbia University will spotlight the Roma people and expand Roma studies by examining topics such as identity and stigma, mobility and displacement, and archival research and digital scholarship. The Project aims to build a digital platform that identifies, examines, and curates material about how Roma define themselves and how others have represented them."
baseurl: "/roma-project" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 406 Schermerhorn Hall, MC 5501; 1190 Amsterdam Ave
city: New York
state: NY
zip_code: 10027
country: United States of America
phone: (917) 327-6534

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
github_url: https://github.com/cristianagrigore/roma-project
instagram_url: https://instagram.com
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
